import Foundation

// MARK: - Code Generator

struct CodeGenerator {
    // MARK: Public API

    func generate(
        _ result: InferenceResult,
        language: TargetLanguage,
        options: GeneratorOptions
    ) -> String {
        switch language {
        case .swift:
            return generateSwift(result, options: options)
        case .kotlin:
            return generateKotlin(result, options: options)
        case .dart:
            return generateDart(result, options: options)
        }
    }

    // MARK: Shared Helpers

    private func models(
        _ result: InferenceResult
    ) -> [(String, [(String, JSONType)])] {
        result.models
            .compactMap { model in
                guard case let .object(name, fields) = model else { return nil }
                return (name, fields)
            }
            .reversed()
    }

    private func swiftIdentifier(for jsonKey: String) -> String {
        let words = jsonKey.split(whereSeparator: isIdentifierSeparator)
        guard let firstWord = words.first else { return "value" }
        guard words.count > 1 else { return String(firstWord) }

        let leadingWord = firstWord.lowercased()
        let remainingWords = words.dropFirst().map(capitalizingFirstLetter)
        return ([leadingWord] + remainingWords).joined()
    }

    private func isIdentifierSeparator(_ character: Character) -> Bool {
        character == "_" || character == "-" || character == " "
    }

    private func capitalizingFirstLetter<S: StringProtocol>(of word: S) -> String {
        guard let firstCharacter = word.first else { return "" }
        return firstCharacter.uppercased() + word.dropFirst()
    }

    // MARK: Swift Generation

    private func swiftType(_ type: JSONType, optional: Bool) -> String {
        let value: String

        switch type {
        case .string:
            value = "String"
        case .integer:
            value = "Int"
        case .number:
            value = "Double"
        case .boolean:
            value = "Bool"
        case .array(let element):
            value = "[\(swiftType(element, optional: false))]"
        case .object(let name, _):
            value = name
        default:
            value = "String"
        }

        return optional || type == .null ? "\(value)?" : value
    }

    private func generateSwift(
        _ result: InferenceResult,
        options: GeneratorOptions
    ) -> String {
        var output = "// Generated by OurJSON\nimport Foundation\n\n"
        let access = options.makeTypesPublic ? "public " : ""
        let declaration = options.construct == .class ? "class" : "struct"
        let sendable = options.markSendable ? ", Sendable" : ""
        let propertyKeyword = options.useVarProperties || options.construct == .class ? "var" : "let"

        for (name, fields) in models(result) {
            output += "\(access)\(declaration) \(name): Codable\(sendable) {\n"

            for (key, type) in fields {
                let property = swiftIdentifier(for: key)
                let valueType = swiftType(type, optional: options.optionalProperties)
                output += "    \(access)\(propertyKeyword) \(property): \(valueType)\n"
            }

            if shouldGenerateCodingKeys(for: fields, options: options) {
                appendCodingKeys(
                    for: fields,
                    useExplicitRawValues: options.explicitCodingKeys,
                    to: &output
                )
            }

            output += "}\n\n"
        }

        return output.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }

    private func appendCodingKeys(
        for fields: [(String, JSONType)],
        useExplicitRawValues: Bool,
        to output: inout String
    ) {
        output += "\n    enum CodingKeys: String, CodingKey {\n"
        for (jsonKey, _) in fields {
            let property = swiftIdentifier(for: jsonKey)
            let needsRawValue = useExplicitRawValues || property != jsonKey

            if needsRawValue {
                output += "        case \(property) = \"\(jsonKey)\"\n"
            } else {
                output += "        case \(property)\n"
            }
        }
        output += "    }\n"
    }

    private func shouldGenerateCodingKeys(
        for fields: [(String, JSONType)],
        options: GeneratorOptions
    ) -> Bool {
        let containsRenamedProperty = fields.contains { jsonKey, _ in
            swiftIdentifier(for: jsonKey) != jsonKey
        }

        if containsRenamedProperty {
            return true
        }

        return options.explicitCodingKeys && !options.plainTypesOnly
    }

    // MARK: Kotlin Generation

    private func kotlinType(_ type: JSONType, optional: Bool) -> String {
        let value: String

        switch type {
        case .string:
            value = "String"
        case .integer:
            value = "Int"
        case .number:
            value = "Double"
        case .boolean:
            value = "Boolean"
        case .array(let element):
            value = "List<\(kotlinType(element, optional: false))>"
        case .object(let name, _):
            value = name
        default:
            value = "String"
        }

        return optional || type == .null ? "\(value)?" : value
    }

    private func generateKotlin(
        _ result: InferenceResult,
        options: GeneratorOptions
    ) -> String {
        var output = "// Generated by OurJSON\n\n"

        for (name, fields) in models(result) {
            output += "data class \(name)(\n"

            for (index, field) in fields.enumerated() {
                let comma = index == fields.count - 1 ? "" : ","
                let type = kotlinType(field.1, optional: options.optionalProperties)
                output += "    val \(field.0): \(type)\(comma)\n"
            }

            output += ")\n\n"
        }

        return output.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }

    // MARK: Dart Generation

    private func dartType(_ type: JSONType, optional: Bool) -> String {
        let value: String

        switch type {
        case .string:
            value = "String"
        case .integer:
            value = "int"
        case .number:
            value = "double"
        case .boolean:
            value = "bool"
        case .array(let element):
            value = "List<\(dartType(element, optional: false))>"
        case .object(let name, _):
            value = name
        default:
            value = "dynamic"
        }

        return optional || type == .null ? "\(value)?" : value
    }

    private func generateDart(
        _ result: InferenceResult,
        options: GeneratorOptions
    ) -> String {
        var output = "// Generated by OurJSON\n\n"

        for (name, fields) in models(result) {
            output += "class \(name) {\n"

            for (key, type) in fields {
                let valueType = dartType(type, optional: options.optionalProperties)
                output += "  final \(valueType) \(key);\n"
            }

            output += "\n  \(name)({\n"
            for key in fields.map(\.0) {
                output += "    required this.\(key),\n"
            }
            output += "  });\n\n"

            output += "  factory \(name).fromJson(Map<String, dynamic> json) => \(name)(\n"
            for (key, type) in fields {
                let valueType = dartType(type, optional: options.optionalProperties)
                output += "    \(key): json['\(key)'] as \(valueType),\n"
            }
            output += "  );\n}\n\n"
        }

        return output.trimmingCharacters(in: .whitespacesAndNewlines) + "\n"
    }
}
